### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by pakutoma** [grafana/k6-template-typescript#38]
The license for this template does not seem to be clearly stated. This means that it is virtually impossible to use this template.
I would expect you to apply an appropriate license to this template, a license that is closer to the public domain, such as CC0.

**Comment by ppcano** [comment]
Hi @pakutoma, thanks for reporting this. 

We have now set the [Apache 2.0 license](https://github.com/grafana/k6-template-typescript/blob/main/LICENSE) on this project. Apache 2.0 is a permissive license that we also use for other public projects. 

Closing by https://github.com/grafana/k6-template-typescript/commit/b7423d92a6d94430bc0890c64daad34a41796bfc

**Comment by pakutoma** [comment]
Thank you so much!!!
