### ISSUE TITLE
TypeScript examples for unit testing modules that use k6/crypto

### ISSUE THREAD

**Issue by DaleMckeown** [grafana/k6-template-typescript#39]
I have a use case where I need to build a module that assists us with our K6 unit tests, this module will reduce code repetition in each of our projects that need load testing. The module imports the `k6/crypto` and uses functions such as `crypto.createHash('sha256')`.

I've managed to get the module built properly using rollup (via Vite) and using TypeScript, and this is compiling to JS correctly and working as expected in our load testing projects.

I want to add some unit tests to the module I have created using `vitest`, to ensure that future changes to not break the implementation. 

I can't seem to add any tests, as soon as I do I get the error:

```
Error: Failed to load url k6/crypto (resolved id: k6/crypto) in path/to/file/src/main.ts. Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-abb4f102.js:54840:21
```

Is there a way for us to be able to unit test NPM packages that utilise k6 modules, or are we not able to do so?

**Comment by ppcano** [comment]
Hi @DaleMckeown,  

The [k6 types](https://www.npmjs.com/package/@types/k6) are implemented on the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/k6).

This project includes tests. We welcome PRs!

Note that for each [new k6 release](https://github.com/grafana/k6/releases), we update the k6 definitions and bump the package version. 

Closing as it seems the issue belongs to the other repo.
